### ISSUE TITLE
[20 SBD] Account Profiles

### ISSUE THREAD

**Issue by Kennybll** [memeit-lol/interface#1]
We would like someone to design and code a profile page for users. The url scheme should be like https://memeit.lol/@kennybll . The main things are showing basic details about the user, like balances, voting power and value, latest memes by them, and their profile image and banner. How ever you design this is up to your discretion but please stay close to the sites look, and the code style scheme.

Languages needing to know are Node.JS, React, CSS, HTML, and Redux.

The code and whatever else your write has to be opensource. Also we may want things changed (as this is to your discretion, but we have the final word) so be prepared for that (though we're not that picky). Also there is a bounty of 20 SBD, so be sure you have a steem account. The bounty is flexible as well.

**Comment by AneilPatel05** [comment]
Just to let everyone know! I am on it.

**Comment by AneilPatel05** [comment]
Completed. please see PR

**Comment by Kennybll** [comment]
Thanks
